import React from 'react';

export default function AssembletWebsite() {
  return (
    <div className="font-sans text-gray-800">
      {/* Hero Section */}
      <section className="bg-amber-50 min-h-screen flex items-center justify-center p-4">
        <div className="text-center">
          <h1 className="text-5xl font-light mb-4">ASSEMBLET SOLUTION</h1>
          <p className="text-2xl font-light">LUXURY INTERIORS TAILORED FOR YOU</p>
        </div>
      </section>

      {/* About Us Section */}
      <section className="py-20 px-4 bg-white">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-light mb-10 text-center">ABOUT US</h2>
          <p className="mb-6 text-lg">
            With our experience in space planning and passion for
            creativity, we take pride in designing and planning
            environments that are ergonomic as well as welcoming to
            ensure that staff and customers enjoy being in the space
            created. We create these spaces by applying decorating
            principals, analysis and integration of knowledge, whereby
            your needs and resources are met, in order to produce an
            interior office space which is attractive, and fulfils the
            project goals. We are involved in varied design fields,
            providing a rich culture of creative, progressive, aesthetic
            and practical design and implementation solution to every
            single creation projects of ours.
          </p>
          <p className="mb-8 text-lg">
            ASSEMBLET SOLUTION is a creative interior design firm
            committed to delivering exceptional spatial experiences.
            Based in DELHI NCR, we specialize in residential,
            commercial, and turnkey interior projects that blend style
            with functionality. Our team brings design concepts to life
            with precision and passion.
          </p>
          <div className="text-center">
            <button className="bg-amber-600 text-white px-6 py-2 rounded hover:bg-amber-700 transition">
              Learn More
            </button>
          </div>
        </div>
      </section>

      {/* Our Vision Section */}
      <section className="py-20 px-4 bg-amber-50">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-light mb-10 text-center">OUR VISION</h2>
          <p className="mb-10 text-lg text-center">
            We envision creating interiors
            that not only look beautiful but
            also enhance everyday living.
            Our goal is to become a trusted
            name in the design industry by
            transforming spaces into
            expressions of personality,
            comfort, and purpose.
          </p>
          
          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-white p-6 rounded shadow">
              <h3 className="text-xl font-medium mb-4">Vision 01</h3>
              <p>
                To transform spaces into
                beautiful, functional
                environments that reflect the
                personality and needs of our
                clients.
              </p>
            </div>
            <div className="bg-white p-6 rounded shadow">
              <h3 className="text-xl font-medium mb-4">Vision 02</h3>
              <p>
                To be recognized as a leading
                provider of interior design and
                facility management services,
                setting the standard for
                quality, innovation, and
                customer satisfaction in the
                industry.
              </p>
            </div>
            <div className="bg-white p-6 rounded shadow">
              <h3 className="text-xl font-medium mb-4">Vision 03</h3>
              <p>
                To create designs that stand the test of time while embracing innovation and sustainable practices.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Our Mission Section */}
      <section className="py-20 px-4 bg-white">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-light mb-10 text-center">OUR MISSION</h2>
          <p className="mb-10 text-lg text-center">
            Our mission is to enhance the quality of life and work
            through exceptional interior design and facility management
            services. We strive to deliver creative, sustainable, and cost-
            effective solutions that reflect our clients' vision while
            exceeding their expectations.
          </p>
          
          <div className="space-y-8">
            <div className="bg-amber-50 p-6 rounded">
              <h3 className="text-xl font-medium mb-4">Mission 01</h3>
              <p>
                Our mission is to offer innovative and customized interior
                solutions tailored to our clients' tastes and lifestyles. We strive
                for excellence in every detail—combining creativity, practicality,
                and top-notch execution within the promised timelines.
              </p>
            </div>
            <div className="bg-amber-50 p-6 rounded">
              <h3 className="text-xl font-medium mb-4">Mission 02</h3>
              <p>
                To create sustainable and environmentally conscious design solutions that harmonize with both client needs and our planet.
              </p>
            </div>
            <div className="bg-amber-50 p-6 rounded">
              <h3 className="text-xl font-medium mb-4">Mission 03</h3>
              <p>
                To deliver personalized interior design solutions with quality
                craftsmanship, creativity, and attention to detail — all while
                respecting timelines and budgets.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Special Design Section */}
      <section className="py-20 px-4 bg-amber-50">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-light mb-10 text-center">SPECIAL DESIGN FOR OUR CLIENT</h2>
          <div className="flex flex-col md:flex-row">
            <div className="md:w-1/2 mb-6 md:mb-0 md:pr-8">
              <p className="text-lg">
                The interior designers at ASSEMBLET
                SOLUTION can remodel your space with
                your specific requirements in mind. The
                space planners at our company make sure
                that we understand the complexities
                involved in your industry and create a
                solution accordingly.
              </p>
            </div>
            <div className="md:w-1/2">
              <p className="text-lg">
                Being able to imagine the space and finally
                gathering the ability to create something
                that is admired by all is a reflection of our
                skills. The ASSEMBLET SOLUTION team
                makes sure that the entire design captures
                all the different qualities that was
                expected of us in the first place.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Why Choose Us Section */}
      <section className="py-20 px-4 bg-white">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-light mb-10 text-center">WHY CHOOSE US?</h2>
          
          <div className="grid md:grid-cols-2 gap-8">
            <div className="bg-amber-50 p-6 rounded">
              <h3 className="text-xl font-medium mb-4">TIMELY DELIVERY</h3>
              <p>
                We are committed to delivering projects on
                time and within budget.
              </p>
            </div>
            <div className="bg-amber-50 p-6 rounded">
              <h3 className="text-xl font-medium mb-4">COMPREHENSIVE CARE</h3>
              <p>
                From initial design to ongoing facility
                management, we offer holistic solutions.
              </p>
            </div>
            <div className="bg-amber-50 p-6 rounded">
              <h3 className="text-xl font-medium mb-4">EXPERT TEAM</h3>
              <p>
                Our professionals bring a wealth of experience and
                expertise to each project.
              </p>
            </div>
            <div className="bg-amber-50 p-6 rounded">
              <h3 className="text-xl font-medium mb-4">CUSTOM SOLUTION</h3>
              <p>
                We understand that every client is
                unique, and we tailor our services
                accordingly.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Our Services Section */}
      <section className="py-20 px-4 bg-amber-50">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-light mb-10 text-center">OUR OFFERED SERVICES</h2>
          
          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-white p-6 rounded shadow">
              <h3 className="text-xl font-medium mb-4">Residential Interior Design</h3>
              <p>
                Crafting personalized living spaces that
                reflect our clients' styles and preferences.
              </p>
            </div>
            <div className="bg-white p-6 rounded shadow">
              <h3 className="text-xl font-medium mb-4">Commercial Interior Design</h3>
              <p>
                Designing functional and inspiring work
                environments that enhance productivity
                and employee well-being.
              </p>
            </div>
            <div className="bg-white p-6 rounded shadow">
              <h3 className="text-xl font-medium mb-4">Turnkey Solutions</h3>
              <p>
                From concept to completion, we handle it
                all so you can relax and enjoy the result.
              </p>
            </div>
            <div className="bg-white p-6 rounded shadow">
              <h3 className="text-xl font-medium mb-4">Space Planning & Layout Design</h3>
              <p>
                We optimize space for maximum utility without
                compromising aesthetics.
              </p>
            </div>
            <div className="bg-white p-6 rounded shadow">
              <h3 className="text-xl font-medium mb-4">Renovation Projects</h3>
              <p>
                Transforming outdated spaces with smart, cost-
                effective upgrades.
              </p>
            </div>
            <div className="bg-white p-6 rounded shadow">
              <h3 className="text-xl font-medium mb-4">Modular Kitchens & Wardrobes</h3>
              <p>
                Efficient, modern, and built for everyday
                functionality.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Photo Gallery Section */}
      <section className="py-20 px-4 bg-white">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-light mb-10 text-center">OUR PHOTO GALLERY</h2>
          
          {/* Placeholder for gallery */}
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {[1, 2, 3, 4, 5, 6].map((item) => (
              <div key={item} className="bg-amber-50 aspect-square flex items-center justify-center">
                <p className="text-amber-800">Gallery Image {item}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Contact Section */}
      <section className="py-20 px-4 bg-amber-50">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-light mb-10 text-center">OUR CONTACT</h2>
          
          <div className="flex flex-col md:flex-row md:space-x-12">
            <div className="md:w-1/2 mb-8 md:mb-0">
              <p className="mb-6 text-lg">
                We'd love to hear from you! Whether you're looking to
                transform your home, office, or commercial space,
                our team is here to guide you through every step of
                the design journey. Let's bring your vision to life.
              </p>
              
              <div className="space-y-4">
                <p className="text-lg"><strong>Phone:</strong> 8368263949</p>
                <p className="text-lg"><strong>Email:</strong> assembletsolution1@gmail.com</p>
                <p className="text-lg"><strong>Address:</strong> Plot.no:- 342, Kingwood Enclave, Sec;-3 wave city, NH-24, Ghaziabad UP</p>
              </div>
            </div>
            
            <div className="md:w-1/2">
              <form className="space-y-4">
                <div>
                  <label className="block mb-2">Name</label>
                  <input type="text" className="w-full p-2 border rounded" placeholder="Your Name" />
                </div>
                <div>
                  <label className="block mb-2">Email</label>
                  <input type="email" className="w-full p-2 border rounded" placeholder="Your Email" />
                </div>
                <div>
                  <label className="block mb-2">Message</label>
                  <textarea className="w-full p-2 border rounded h-32" placeholder="Your Message"></textarea>
                </div>
                <button type="submit" className="bg-amber-600 text-white px-6 py-2 rounded hover:bg-amber-700 transition">
                  Send Message
                </button>
              </form>
            </div>
          </div>
        </div>
      </section>

      {/* Thank You/Footer Section */}
      <section className="py-12 px-4 bg-amber-800 text-white">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl font-light mb-4">THANK YOU</h2>
          <p className="mb-6">
            Thank you for reaching out to ASSEMBLET SOLUTION.
            We appreciate your interest in our interior design services 
            and look forward to learning more about your space and vision. 
            Our team will get in touch with you shortly to discuss how we can 
            bring your ideas to life.
          </p>
          <p className="mb-8">
            Until then, feel free to explore our portfolio or follow us on 
            social media for inspiration.
          </p>
          <p className="font-light text-xl">Let's design something beautiful together!</p>
          
          <div className="mt-8 flex justify-center space-x-6">
            <a href="#" className="text-white hover:text-amber-200 transition">
              <span className="sr-only">Facebook</span>
              <svg className="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path fillRule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clipRule="evenodd" />
              </svg>
            </a>
            <a href="#" className="text-white hover:text-amber-200 transition">
              <span className="sr-only">Instagram</span>
              <svg className="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path fillRule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clipRule="evenodd" />
              </svg>
            </a>
          </div>
          
          <p className="mt-8 text-sm opacity-75">© 2025 ASSEMBLET SOLUTION. All rights reserved.</p>
        </div>
      </section>
    </div>
  );
}
